### ISSUE TITLE
Partials without layout keep using layout from previously loaded partial

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Launcher#181] opened 2016-01-12 10:36 UTC
If an app (Products) has two partials, one with layout setup, another one without any setup, then the following issue occurs:

1. Open the partial with layout setup.
2. Redirect to partial without layout setup with `puppet-redirect`.
3. The new loaded partial keeps using the setup from the partial in step 1.

By @tomalec on HO

>ok so if there is no layout for the new one layoiut should be JSON Patched to empty, instead of beeing kept unchanged

**Comment by tomalec** [comment] 2016-01-12 10:53
1. Go to http://douglas-11.mysampleapp.com/products:
    - Products page (`PartialId: '/Products/viewmodels/ProductListPage.html'`) content is loaded as `/workspaces/0/Products/CurrentPage`,
    - no layout gets attached as there is no layout specified yet.
2. Redirect to http://douglas-11.mysampleapp.com/products/product/K
  - Product page is loaded (`PartialId: '/Products/viewmodels/EditProductPage.html'`) as `/workspaces/0/Products/CurrentPage`
  - Some layout gets attached from `/workspaces/0/Products/CurrentPage/layout`
3. Go back to http://douglas-11.mysampleapp.com/products with SPA redirect
  -  `/workspaces/0/Products/CurrentPage` gets patched back to Products page
  -  `/workspaces/0/Products/CurrentPage/layout` become unspecified once again

I susspect following reasons:
 - because layout is falsy again, some binding may treat it as "no-change",
 - because there was no direct patch on `/workspaces/0/Products/CurrentPage/layout` something was not notified, or
 - this is the legacy from times when layouts were fetched outside of puppet frolw with XHRs, plus there were no way to return null, so we were not able to distinguish change to unspecified layout (nothing in XHR response, nothing in Puppet view-model), from XHR not yet come (nothing in view-model).

**Comment by tomalec** [comment] 2016-04-07 17:37
I think got it. 
@warpech when you were adding `launcher-include` into Polymer's notification flow, did you also covered notifying itself (inner `juicy-tile-*`)?
https://github.com/PuppetJs/puppet-polymer-client/issues/12
https://github.com/StarcounterPrefabs/launcher-include/blob/gh-pages/starcounter-include.html#L174

**Comment by tomalec** [comment] 2016-04-08 08:04
Sorry, that was me, who add notifications there  :no_mouth: I'll try to fix it before I leave for vacations

**Comment by tomalec** [comment] 2016-04-08 16:01
Unfortunatelly, I didn't manage to do it today. I think making `starcounter-include` a Polymer element should solve this problem.

When nested partial is replaced as a entire object, it's not notified about PartialId and Layout changes.

Then when we make it as Polymer element we can use `observers: [ 'updatePartialId(partial.Launcher.PartialId)', 'updateLayout(partial.Launcher.Layout)' ]`

**Comment by miyconst** [comment] 2016-04-08 18:57
I would like to keep `starcounter-include` as a clean element, but if it is required to make as a Polymer element I am also fine.

**Comment by warpech** [comment] 2016-04-11 08:13
We are talking here only about making [Launcher's starcounter-include](https://github.com/StarcounterPrefabs/launcher-include) a Polymer element.

**Comment by warpech** [comment] 2016-04-12 09:36
I think there is a way to implement it only using `_notifyPath`, without converting to a Polymer element.

But there is a problem - I can't reproduce it. See the screen recording below. If I understand the problem correctly, the red background from "Product details" should be used for the "Product" heading when I morph to the products list.

How can I visually reproduce it with the Procucts app?

![bug](https://cloud.githubusercontent.com/assets/566463/14455948/ab792b52-00a2-11e6-9478-03e3e197b786.gif)

**Comment by miyconst** [comment] 2016-04-12 10:21
>How can I visually reproduce it with the Products app?

1. Start Products & Launcher apps.
2. Delete all layout styles by executing `DELETE FROM Starcounter.Layout`.
3. Add `background: red;` to the Products header `juicy-style`.
4. Open `http://localhost:8080/products`. **The header is red - correct.**
5. Click Add new product button.
6. **The header is also red - wrong.**
7. Click Cancel button.
8. **The header is no longer red - wrong.**

**Comment by warpech** [comment] 2016-04-12 10:35
I can confirm this is reproducible now. Thanks for the instructions!

Actually I don't think that the problem is in Launcher's `starcounter-include` anymore. On this branch [fix_SignIn_workspace_switching_224](https://github.com/StarcounterPrefabs/Launcher/tree/fix_SignIn_workspace_switching_224) the notification works properly. The line [starcounter-include.html#L141](https://github.com/StarcounterPrefabs/Launcher/blob/fix_SignIn_workspace_switching_224/src/Launcher/wwwroot/sys/starcounter-include/starcounter-include.html#L141) gets executed when you run step (5) from above. 

The problem must be that `juicy-tile-table` (and/or `juicy-tiles-setup-sync`?) does not observe when the `setup` property is replaced. Maybe some method needs to be called on it to force refreshing?

**Comment by warpech** [comment] 2016-04-12 11:19
I know what is going on. When Launcher's `starcounter-include` replaces the partial, `juicy-tile-list` executes the `createItemsList` method, which reads `juicy-setup` attributes from DOM.

BUT! The new partial is not yet asynchronously loaded, meaning the current DOM elements still represent the old partial, not the new partial.

The solution is to change `imported-template` to clear the previous DOM elements at the time of request for the new HTML (now it is cleared at the time of response). But this will contribute to having blank page displayed during loading of the partial. 

Any better ideas?

**Comment by warpech** [comment] 2016-04-12 11:36
The proposed fix is available for preview in the commit https://github.com/StarcounterPrefabs/Launcher/commit/4e9c8d588fffee14d0bec88dcf9d2887e5375356. @miyconst, @tomalec could you please review?

**Comment by miyconst** [comment] 2016-04-12 22:00
When running apps on localhost, I don't notice any white space blinking, and even if there are some hard blinking, it is still better to have blinking and working solution than artifacts on the page.

**Comment by warpech** [comment] 2016-04-13 09:26
I will try a less invasive method that does not require changing `imported-template`. 

I will just call `this.template.clear()` before line: https://github.com/StarcounterPrefabs/Launcher/blob/d7a0fffb03c4204a77dc37fae8c0825ac89774a9/src/Launcher/wwwroot/sys/starcounter-include/starcounter-include.html#L138

**Comment by warpech** [comment] 2016-04-13 10:35
`master` branch updated with work in progress of changes to Launcher's `starcounter-include`. The only missing part is to write tests and release through bower.

**Comment by warpech** [comment] 2016-04-13 16:24
This is fixed in Launcher 4.0.1

**Closed by warpech** 2016-04-13 16:24 UTC
Labels: bug

**Comment by miyconst** [comment] 2016-04-14 08:05
I confirm, the issue is solved. Thank you @warpech.
