### ISSUE TITLE
Adding fields breaks layout for existing fields

### ISSUE THREAD

**Issue by Joltrix** [StarcounterPrefabs/Launcher#242] opened 2016-08-31 09:37 UTC
@tomalec 

When you change one of the values on the custom fields, it breaks the layout as the content is refreshed.
The same thing happens when you add a field, be it custom, phone number, address or email. The layout for the existing fields becomes distorted as can be seen on the gif provided by @warpech 

![screen](https://cloud.githubusercontent.com/assets/566463/18123388/e221de58-6f6d-11e6-8647-2eae218abdb8.gif)

**Comment by tomalec** [comment] 2016-08-31 11:16
Reported at https://github.com/StarcounterSamples/People/pull/40#issuecomment-243708614

**Comment by Joltrix** [comment] 2016-09-01 07:11
@tomalec 

When you say blank page, you mean you can't see anything at all :o? 

Cause, it can be reproduced in both develop, feature/people-improvements and feature/further-enhancement, those 3 I am sure of, I haven't tried any of the other builds.

But i suspect that you can't reproduce it on the Master build. I think the issue arose when @warpech fixed the Layout, because when the layout gets "broken", it basically "reverts" to how it was before the latest visual update.

**Comment by tomalec** [comment] 2016-09-01 14:57
That is all I can see with:
- Starcounter: 2.2.1.3004
- StarcounterPrefabs/Launcher@9c506c66a6c
- StarcounterSamples/People@e784dbfce

![image](https://cloud.githubusercontent.com/assets/17435/18172243/f88aec96-7064-11e6-8f54-ac046c0165d4.png)

**Comment by Joltrix** [comment] 2016-09-01 15:01
I dont know if it will make a difference, but I also start SignIn and UserAdmin, and log in ad admin/admin

**Comment by tomalec** [comment] 2016-09-01 15:32
Probably it does, however even after I run those I cannot login as admin/admin.

BTW, @warpech do we really want People app show blank page without a single message for not logged in users?

**Comment by tomalec** [comment] 2016-09-01 15:48
My bad, I missed https://github.com/StarcounterSamples/People#installation-instructions

**Comment by warpech** [comment] 2016-09-01 16:09
> BTW, @warpech do we really want People app show blank page without a single message for not logged in users?

No, we don't really want that. @joozek78 is working on more clever authentincation and authorization scheme. Then we can decide how to actually inform a user that they need to log in.

**Comment by tomalec** [comment] 2016-09-01 22:48
I have identified the problem, it was a bug in `starcounter-include` https://github.com/StarcounterPrefabs/launcher-include/issues/18 (fix is ready, I just need to add some tests).

It also showed up because of the fact People app replaces entire table instead of pushing one element. That's not the reason but I would also call it a bug https://github.com/StarcounterSamples/People/issues/42

**Comment by warpech** [comment] 2016-09-02 10:26
Thanks!

**Comment by warpech** [comment] 2016-09-12 09:44
@tomalec was the solution released with Starcounter?

I can still reproduce it at http://inside.starcounter.com/, which is using Starcounter 2.2.1.3133 and Launcher 5.0.0-develop.2

Can you pls take a look?

**Comment by tomalec** [comment] 2016-09-12 10:28
Could you provide credentials for http://inside.starcounter.com/people/persons ?

**Comment by tomalec** [comment] 2016-09-12 13:07
So it seems either it's not this version of Starcounter or some other app overwrites the `starcounter-include` as the [one from `/sys`](https://github.com/Starcounter/Starcounter/blob/develop/src/BuildSystem/ClientFiles/StaticFiles/sys/starcounter-include/starcounter-include.html) is 1.3.0 but the one at http://inside.starcounter.com/sys/starcounter-include/starcounter-include.html is just 1.0.1

**Comment by warpech** [comment] 2016-09-12 13:59
This was my bad. `Launcher 5.0.0-develop.1` package included outdated `starcounter-include`.

I have re-released the package and updated http://inside.starcounter.com/

Works OK now

**Closed by warpech** 2016-09-12 13:59 UTC
